services:
  app:
    build: .
    volumes:
      - .:/var/www
    ports:
      - "9000:9000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_DATABASE=sheba_xyz
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    networks:
      - sheba_xyz

  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: sheba_xyz
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - sheba_xyz
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      app:
        condition: service_started
    networks:
      - sheba_xyz

networks:
  sheba_xyz:
    driver: bridge

volumes:
  dbdata: