version: '3.8'
services:
  app:
    build: .
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_DATABASE=booking
      - DB_USERNAME=root
      - DB_PASSWORD=secret
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: booking
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata: